spring:
  datasource:
    url: jdbc:mysql://49.232.222.169:3306/campus?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: campus
    password: campus123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 30000
  redis:
    host: 49.232.222.169
    port: 6379
    password: ljh819918
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
    database: 0
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 9090
shiro-redis:
  enabled: true
  redis-manager:
    host: 49.232.222.169:6379
    password: ljh819918
markerhub:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization
# 设置最大支持文件大小
servlet:
  multipart:
    max-file-size: 100MB
    max-request-size: 1000MB
# 阿里云存储
# endPoint
aliyun:
  endPoint: oss-cn-beijing.aliyuncs.com
# Bucket
  urlPrefix: http://landstar.oss-cn-beijing.aliyuncs.com
# accessKey Id
  accessKeyId: LTAI5t7BJj2p4tDKgn8TSzqy
# accessKey Secret
  accessKeySecret: 2aVQV3mTxehdD03T0KaluF4b6IEoIY
# BucketName
  bucketName: landstar
# 腾讯云验证码
tencent:
  msm:
    id: AKIDNZZOzeI2f44ysJcjcKnDVo8RiyBIExqh
    secret: pbbZadXxAAzd8VhgfV9d2LUWM4au0zpT
    appId: 1400791565
    signName: 星屿阁个人网
    templateId: 1672106


