spring:
  datasource:
    url: jdbc:mysql://49.232.222.169:3306/campus?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: campus
    password: campus123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 30000
  redis:
    host: 49.232.222.169
    port: 6379
    password: ljh819918
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
    database: 0
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 9090
shiro-redis:
  enabled: true
  redis-manager:
    host: 49.232.222.169:6379
    password: ljh819918
markerhub:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization